In [1]:
import pandas as pd
df=pd.read_csv("online_retail_practice_sample.csv")
del df['InvoiceDate']
df.to_csv("Phase2.csv",index=False)

In [5]:
dm=df.head(10)
dm.to_excel("Top_10_Files.xlsx",index=False)
dm

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,4.07,12343.0,Spain
6,570510,POST,POSTAGE,4,14.40,12767.0,United Kingdom
7,574557,POST,POSTAGE,1,21.60,13566.0,France
8,572698,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2,0.55,14765.0,Germany
9,547022,71053,WHITE METAL LANTERN,7,4.07,15256.0,EIRE

In [3]:
dp=df[['Quantity','UnitPrice']].mean()
dd=df[['Quantity','UnitPrice']].median()
dl=df[['Quantity','UnitPrice']].mode()
print("Mean")
print(dp)
print("--------------------------------------------------------------------------------------------------------------------")
print("Median")
print(dd)
print("-----------------------------------------------------------------------------------------------------------------------------")
print("Mode")
print(dl)

Mean
Quantity     7.158189
UnitPrice    5.523189
dtype: float64
--------------------------------------------------------------------------------------------------------------------
Median
Quantity     8.00
UnitPrice    3.39
dtype: float64
-----------------------------------------------------------------------------------------------------------------------------
Mode
   Quantity  UnitPrice
0        15       0.55

In [15]:
df.describe()

          Quantity    UnitPrice    CustomerID
count  1612.000000  1612.000000   1541.000000
mean      7.158189     5.523189  15201.415315
std       5.890089     5.191564   1693.230069
min     -15.000000     0.000000  12305.000000
25%       4.000000     2.200000  13708.000000
50%       8.000000     3.390000  15220.000000
75%      12.000000     7.650000  16640.000000
max      15.000000    21.600000  18196.000000

In [18]:
df[["Country","Description"]].describe()

       Country Description
count     1599        1589
unique      10          22
top     France     POSTAGE
freq       178         143

In [20]:
info=df.info()
info

<class 'pandas.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1612 non-null   str
 1   StockCode    1612 non-null   str
 2   Description  1589 non-null   str
 3   Quantity     1612 non-null   int64
 4   UnitPrice    1612 non-null   float64
 5   CustomerID   1541 non-null   float64
 6   Country      1599 non-null   str
dtypes: float64(2), int64(1), str(4)
memory usage: 88.3 KB

In [36]:
miss=df.isnull().sum()
miss

InvoiceNo       0
StockCode       0
Description    23
Quantity        0
UnitPrice       0
CustomerID     71
Country        13
dtype: int64

In [49]:
invoice=df['InvoiceNo'].unique()
Des=df['Description'].unique()
Cus=df['CustomerID'].unique()
Cou=df['Country'].unique()
print(invoice)
print("-------------------------------------------------------------------------------------------------------------")
print(Des)
print("--------------------------------------------------------------------------------------------------------------")
print(Cus)
print("--------------------------------------------------------------------------------------------------------------")
print(Cou)
result = pd.DataFrame({
    'InvoiceNo': pd.Series(invoice),
    'Description': pd.Series(Des),
    'CustomerID': pd.Series(Cus),
    'Country': pd.Series(Cou)
})
result.to_excel("Result_File.xlsx",index=False)

<StringArray>
[ '570338',  '574674',  '545052',  '567005',  '573512',  '561166',  '570510',
  '574557',  '572698',  '547022',
 ...
  '559197',  '569288', 'C542886',  '560762',  '566112',  '564607',  '576989',
 'C555041',  '567397',  '570077']
Length: 1574, dtype: str
-------------------------------------------------------------------------------------------------------------
<StringArray>
[                  'WHITE METAL LANTERN',
     'GLASS STAR FROSTED T-LIGHT HOLDER',
   'KNITTED UNION FLAG HOT WATER BOTTLE',
                               'POSTAGE',
    'PACK OF 60 PINK PAISLEY CAKE CASES',
                'HAND WARMER UNION JACK',
       'PACK OF 72 RETROSPOT CAKE CASES',
          'SET 7 BABUSHKA NESTING BOXES',
              'REGENCY CAKESTAND 3 TIER',
                    'PINK CHERRY LIGHTS',
    'WHITE HANGING HEART T-LIGHT HOLDER',
        'CREAM CUPID HEARTS COAT HANGER',
                                     nan,
  ' PACK OF 60 PINK PAISLEY CAKE CASES ',
      ' CREAM CUPID HEARTS COAT HANGER ',
        ' SET 7 BABUSHKA NESTING BOXES ',
  ' WHITE HANGING HEART T-LIGHT HOLDER ',
 ' KNITTED UNION FLAG HOT WATER BOTTLE ',
                             ' POSTAGE ',
              ' HAND WARMER UNION JACK ',
                  ' PINK CHERRY LIGHTS ',
     ' PACK OF 72 RETROSPOT CAKE CASES ',
   ' GLASS STAR FROSTED T-LIGHT HOLDER ']
Length: 23, dtype: str
--------------------------------------------------------------------------------------------------------------
[16640. 17154. 16783. ... 14111. 17260. 12345.]
--------------------------------------------------------------------------------------------------------------
<StringArray>
[        'Sweden',    'Netherlands',          'Spain', 'United Kingdom',
         'France',        'Germany',           'EIRE',       'Portugal',
        'Belgium',      'Australia',              nan]
Length: 11, dtype: str

In [60]:
dp=pd.read_csv("Phase2.csv")
Cou=dp['Country'].value_counts()
top=Cou.head(10)
print(top)

Country
France            178
Spain             165
Australia         165
Belgium           164
Sweden            162
United Kingdom    160
Netherlands       158
EIRE              155
Portugal          147
Germany           145
Name: count, dtype: int64

In [64]:
top.to_excel("Top_10_Countries.xlsx", header=["Transactions"])

In [72]:
row=df.shape[0]
col=df.shape[1]
uniq_Description=df['Description'].unique()
uniq_Invoice=df['InvoiceNo'].unique()
print(row)
print(col)
print(uniq_Description)
print(uniq_Invoice)
dm=pd.DataFrame({
    'Rows':pd.Series(row),
    'Columns':pd.Series(col),
    'Describ':pd.Series(uniq_Description),
    'Invoice':pd.Series(uniq_Invoice)
})
dm.to_excel("Res_4.xlsx",index=False)

1612
7
<StringArray>
[                  'WHITE METAL LANTERN',
     'GLASS STAR FROSTED T-LIGHT HOLDER',
   'KNITTED UNION FLAG HOT WATER BOTTLE',
                               'POSTAGE',
    'PACK OF 60 PINK PAISLEY CAKE CASES',
                'HAND WARMER UNION JACK',
       'PACK OF 72 RETROSPOT CAKE CASES',
          'SET 7 BABUSHKA NESTING BOXES',
              'REGENCY CAKESTAND 3 TIER',
                    'PINK CHERRY LIGHTS',
    'WHITE HANGING HEART T-LIGHT HOLDER',
        'CREAM CUPID HEARTS COAT HANGER',
                                     nan,
  ' PACK OF 60 PINK PAISLEY CAKE CASES ',
      ' CREAM CUPID HEARTS COAT HANGER ',
        ' SET 7 BABUSHKA NESTING BOXES ',
  ' WHITE HANGING HEART T-LIGHT HOLDER ',
 ' KNITTED UNION FLAG HOT WATER BOTTLE ',
                             ' POSTAGE ',
              ' HAND WARMER UNION JACK ',
                  ' PINK CHERRY LIGHTS ',
     ' PACK OF 72 RETROSPOT CAKE CASES ',
   ' GLASS STAR FROSTED T-LIGHT HOLDER ']
Length: 23, dtype: str
<StringArray>
[ '570338',  '574674',  '545052',  '567005',  '573512',  '561166',  '570510',
  '574557',  '572698',  '547022',
 ...
  '559197',  '569288', 'C542886',  '560762',  '566112',  '564607',  '576989',
 'C555041',  '567397',  '570077']
Length: 1574, dtype: str