In [1]:
import pandas as pd
df=pd.read_csv("online_retail_practice_sample.csv")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [2]:
dm=df[['InvoiceNo','InvoiceDate']]
dm

     InvoiceNo          InvoiceDate
0       570338  2011-09-15 15:26:00
1       574674  2011-06-05 08:10:00
2       545052  2011-07-24 03:45:00
3       567005  2011-09-04 16:55:00
4       573512  2011-02-23 13:40:00
...        ...                  ...
1607    546730  2011-09-20 00:21:00
1608    556479  2011-11-13 09:05:00
1609   C541876  2011-04-07 12:48:00
1610    553299  2011-09-24 16:24:00
1611    537515  2011-08-24 00:48:00

[1612 rows x 2 columns]

In [3]:
dl=df[df["Quantity"]>10]
dl.to_excel("Quantity_greater_10

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
10,567596,22633,HAND WARMER UNION JACK,15,2011-07-24 14:21:00,1.68,15220.0,France
18,580659,79323P,PINK CHERRY LIGHTS,15,2011-06-11 21:15:00,8.10,18019.0,Sweden
...,...,...,...,...,...,...,...,...
1593,560762,21730,GLASS STAR FROSTED T-LIGHT HOLDER,11,2011-07-22 02:33:00,4.25,15530.0,Belgium
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.60,13594.0,United Kingdom
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE

In [4]:
dn=df.iloc[0:10,0:4]
dn

  InvoiceNo StockCode                          Description  Quantity
0    570338     71053                  WHITE METAL LANTERN         7
1    574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
2    545052    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         0
3    567005     71053                  WHITE METAL LANTERN        12
4    573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
5    561166    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         3
6    570510      POST                              POSTAGE         4
7    574557      POST                              POSTAGE         1
8    572698     21977   PACK OF 60 PINK PAISLEY CAKE CASES         2
9    547022     71053                  WHITE METAL LANTERN         7

In [5]:
dm=df.loc[3]
dm

InvoiceNo                   567005
StockCode                    71053
Description    WHITE METAL LANTERN
Quantity                        12
InvoiceDate    2011-09-04 16:55:00
UnitPrice                     3.39
CustomerID                 14222.0
Country                      Spain
Name: 3, dtype: object

In [9]:
dd=df[df['UnitPrice']>20]
dd.to_csv("price_greater_20.csv")

In [8]:
ds=df[df['Country']=='France']
ds.to_excel("Single_Country_data.xlsx")