In [3]:
import pandas as pd
df=pd.read_csv("online_retail_practice_sample.csv")
df.size

12896

In [20]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden

In [5]:
df.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1602,576798,22633,HAND WARMER UNION JACK,8,2011-03-20 15:46:00,2.10,16068.0,Australia
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-05-25 22:09:00,3.40,13436.0,Portugal
1604,565607,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,2011-07-24 17:52:00,2.71,13346.0,Netherlands
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,2011-04-19 21:53:00,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,2011-08-16 02:22:00,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [9]:
# 15 random values

df.sample(15,random_state=42)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
29,565045,22752,SET 7 BABUSHKA NESTING BOXES,8,2011-10-05 07:59:00,7.65,17321.0,Netherlands
259,544497,POST,POSTAGE,2,2010-12-10 14:46:00,21.60,15411.0,France
383,539123,71053,WHITE METAL LANTERN,12,2011-02-09 04:06:00,4.07,14097.0,France
425,565669,79323P,PINK CHERRY LIGHTS,14,2011-07-13 11:38:00,5.40,14394.0,EIRE
239,559785,71053,WHITE METAL LANTERN,8,2011-08-20 18:01:00,4.07,17429.0,Sweden
787,562769,21977,PACK OF 60 PINK PAISLEY CAKE CASES,11,2011-03-16 12:30:00,0.66,12969.0,Australia
1471,544897,21977,PACK OF 60 PINK PAISLEY CAKE CASES,8,2011-07-18 18:26:00,0.55,18175.0,Portugal
497,561669,21730,GLASS STAR FROSTED T-LIGHT HOLDER,8,2011-02-01 01:20:00,4.25,14894.0,Spain
495,566207,21212,PACK OF 72 RETROSPOT CAKE CASES,11,2011-08-29 00:28:00,0.55,14557.0,France
754,568872,84406B,CREAM CUPID HEARTS COAT HANGER,12,2011-09-12 09:05:00,3.30,14377.0,United Kingdom
411,572532,21977,PACK OF 60 PINK PAISLEY CAKE CASES,1,2011-07-20 17:18:00,0.55,16634.0,Germany
1581,552090,21730,GLASS STAR FROSTED T-LIGHT HOLDER,9,2011-01-19 21:03:00,5.10,13181.0,France
720,C537033,22752,SET 7 BABUSHKA NESTING BOXES,-5,2011-08-03 23:56:00,7.65,16639.0,United Kingdom
247,576014,85123A,WHITE HANGING HEART T-LIGHT HOLDER,5,2011-06-11 17:56:00,2.04,12691.0,United Kingdom
567,547774,79323P,PINK CHERRY LIGHTS,13,2011-01-24 11:59:00,5.40,14055.0,Netherlands

In [17]:
# Print the rows and columns

df.size

12896

In [12]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [16]:
# Original ds values

df.shape

(1612, 8)

In [14]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [15]:
df['Description'].head(20)

0                     WHITE METAL LANTERN
1       GLASS STAR FROSTED T-LIGHT HOLDER
2     KNITTED UNION FLAG HOT WATER BOTTLE
3                     WHITE METAL LANTERN
4     KNITTED UNION FLAG HOT WATER BOTTLE
5     KNITTED UNION FLAG HOT WATER BOTTLE
6                                 POSTAGE
7                                 POSTAGE
8      PACK OF 60 PINK PAISLEY CAKE CASES
9                     WHITE METAL LANTERN
10                 HAND WARMER UNION JACK
11        PACK OF 72 RETROSPOT CAKE CASES
12                                POSTAGE
13           SET 7 BABUSHKA NESTING BOXES
14      GLASS STAR FROSTED T-LIGHT HOLDER
15     PACK OF 60 PINK PAISLEY CAKE CASES
16                                POSTAGE
17               REGENCY CAKESTAND 3 TIER
18                     PINK CHERRY LIGHTS
19               REGENCY CAKESTAND 3 TIER
Name: Description, dtype: str